"""Typing stubs for the optional `palfrey_rust` extension module."""

from __future__ import annotations

def parse_header_items(headers: list[str]) -> list[tuple[str, str]]: ...
def split_csv_values(value: str) -> list[str]: ...
def parse_request_head(data: bytes) -> tuple[str, str, str, list[tuple[str, str]]]: ...
def unmask_websocket_payload(payload: bytes | bytearray | memoryview, masking_key: bytes) -> bytes: ...
